build:
  image: centos:7
  commands:
#    - yum install -y epel-release
#    - yum install -y nodejs npm
#    - npm -d install
#    - npm install -g mocha
#    - mocha
#
deploy:
  rsync:
    user: walsh
    host: 192.168.99.1
    port: 22
    source: *
    target: /tmp/nodejs-helloworld
    delete: false
    recursive: true
    exclude:
      - "test/*"
    commands:
      - cd /tmp/nodejs-helloworld
      - node server
#  ssh:
#    host: 192.168.99.1
#    port: 22
#    user: walsh
#    commands:
#      - 

