build:
  image: centos:7
  commands:
    - yum install -y epel-release
    - yum install -y nodejs npm
    - npm -d install
    - npm install -g mocha
    - mocha
deploy:
  # if the branch is master
  rsync:
    user: walsh
    host: 192.168.99.1
    port: 22
    source: .
    target: /tmp
    delete: false
    recursive: true
    exclude:
      - "test/*"
    commands:
      - cd /tmp/nodejs-helloworld
      - killall -KILL node >/dev/null 2>&1
      - sh -c '/usr/local/bin/node server &' &
    when:
      branch: [master]
