build:
  image: centos:7
  commands:
    - yum install -y epel-release
    - yum install -y nodejs
    - yum install -y npm
    - npm -d install
    - npm test
    - npm install -g mocha
    - mocha

