build:
  image: centos:7
  commands:
    - yum install -y epel-release
    - yum install -y nodejs npm
    - npm -d install
    - npm install -g mocha
    - mocha
deploy:
  # if the branch is master
  rsync:
    user: walsh
    host: 192.168.99.1
    port: 22
    source: .
    target: /tmp/rsync/
    delete: false
    recursive: true
    exclude:
      - "test/*"
    commands:
      - cp -Rf /tmp/rsync/nodejs-helloworld /tmp/nodejs-helloworld
      - cd /tmp/nodejs-helloworld
      - ./run restart
    when:
      branch: [master]
